/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'

const SettingsLazyRouteImport = createFileRoute('/settings')()
const PricingLazyRouteImport = createFileRoute('/pricing')()
const LoginLazyRouteImport = createFileRoute('/login')()
const KeysLazyRouteImport = createFileRoute('/keys')()
const EventsLazyRouteImport = createFileRoute('/events')()
const IndexLazyRouteImport = createFileRoute('/')()

const SettingsLazyRoute = SettingsLazyRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/settings.lazy').then((d) => d.Route))
const PricingLazyRoute = PricingLazyRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/pricing.lazy').then((d) => d.Route))
const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const KeysLazyRoute = KeysLazyRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/keys.lazy').then((d) => d.Route))
const EventsLazyRoute = EventsLazyRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/events.lazy').then((d) => d.Route))
const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/events': typeof EventsLazyRoute
  '/keys': typeof KeysLazyRoute
  '/login': typeof LoginLazyRoute
  '/pricing': typeof PricingLazyRoute
  '/settings': typeof SettingsLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/events': typeof EventsLazyRoute
  '/keys': typeof KeysLazyRoute
  '/login': typeof LoginLazyRoute
  '/pricing': typeof PricingLazyRoute
  '/settings': typeof SettingsLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/events': typeof EventsLazyRoute
  '/keys': typeof KeysLazyRoute
  '/login': typeof LoginLazyRoute
  '/pricing': typeof PricingLazyRoute
  '/settings': typeof SettingsLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/events' | '/keys' | '/login' | '/pricing' | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/events' | '/keys' | '/login' | '/pricing' | '/settings'
  id:
    | '__root__'
    | '/'
    | '/events'
    | '/keys'
    | '/login'
    | '/pricing'
    | '/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  EventsLazyRoute: typeof EventsLazyRoute
  KeysLazyRoute: typeof KeysLazyRoute
  LoginLazyRoute: typeof LoginLazyRoute
  PricingLazyRoute: typeof PricingLazyRoute
  SettingsLazyRoute: typeof SettingsLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/keys': {
      id: '/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof KeysLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  EventsLazyRoute: EventsLazyRoute,
  KeysLazyRoute: KeysLazyRoute,
  LoginLazyRoute: LoginLazyRoute,
  PricingLazyRoute: PricingLazyRoute,
  SettingsLazyRoute: SettingsLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
