/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as RequestsRouteImport } from './routes/requests'

const IndexLazyRouteImport = createFileRoute('/')()
const LoginLazyRouteImport = createFileRoute('/login')()
const OperationsLazyRouteImport = createFileRoute('/operations')()
const ReferenceLazyRouteImport = createFileRoute('/reference')()

const IndexLazyRoute = IndexLazyRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const LoginLazyRoute = LoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const OperationsLazyRoute = OperationsLazyRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/operations.lazy').then((d) => d.Route))
const ReferenceLazyRoute = ReferenceLazyRouteImport.update({
  id: '/reference',
  path: '/reference',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/reference.lazy').then((d) => d.Route))
const RequestsRoute = RequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/requests.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexLazyRoute
  '/requests': typeof RequestsRoute
  '/login': typeof LoginLazyRoute
  '/operations': typeof OperationsLazyRoute
  '/reference': typeof ReferenceLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexLazyRoute
  '/requests': typeof RequestsRoute
  '/login': typeof LoginLazyRoute
  '/operations': typeof OperationsLazyRoute
  '/reference': typeof ReferenceLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexLazyRoute
  '/requests': typeof RequestsRoute
  '/login': typeof LoginLazyRoute
  '/operations': typeof OperationsLazyRoute
  '/reference': typeof ReferenceLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/requests' | '/login' | '/operations' | '/reference'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/requests' | '/login' | '/operations' | '/reference'
  id: '__root__' | '/' | '/requests' | '/login' | '/operations' | '/reference'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  RequestsRoute: typeof RequestsRoute
  LoginLazyRoute: typeof LoginLazyRoute
  OperationsLazyRoute: typeof OperationsLazyRoute
  ReferenceLazyRoute: typeof ReferenceLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reference': {
      id: '/reference'
      path: '/reference'
      fullPath: '/reference'
      preLoaderRoute: typeof ReferenceLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests': {
      id: '/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof RequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  RequestsRoute: RequestsRoute,
  LoginLazyRoute: LoginLazyRoute,
  OperationsLazyRoute: OperationsLazyRoute,
  ReferenceLazyRoute: ReferenceLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
